// Copyright (c) 2025 Pratik Barhate
// Licensed under the MIT License. See the LICENSE file in the project root for more information.

//! Raw, unsafe FFI declarations for the ONNX Runtime C API.
//!
//! Everything in this module is generated by `bindgen` from
//! `headers/onnxruntime_c_api.h` (ONNX Runtime v1.29.0, `ORT_API_VERSION` 29).
//! Nothing here is hand-edited.
//!
//! By default the checked-in `src/bindings/ort.rs` is included so the crate
//! builds without libclang. Build with `--features bindgen` to regenerate from
//! the header instead.
//!
//! bindgen emits compile-time layout assertions (`const _: () = { .. }`) for
//! every struct with a known layout, so a struct size, alignment, or field
//! offset that disagrees with the header is a hard compile error rather than a
//! silent memory-safety bug.
//!
//! Prefer the safe wrappers in the crate root over calling into this module.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    // bindgen's `__IncompleteArrayField` helpers call `slice::from_raw_parts`
    // directly in the body of an `unsafe fn`, which edition 2024 flags. The
    // generated code is not ours to restructure.
    unsafe_op_in_unsafe_fn,
    clippy::all
)]

#[cfg(feature = "bindgen")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(not(feature = "bindgen"))]
include!("bindings/ort.rs");
