// Copyright (c) 2025 Pratik Barhate
// Licensed under the MIT License. See the LICENSE file in the project root for more information.
//
// @generated by bindgen 0.72.1 from headers/wrapper.h. DO NOT EDIT BY HAND.
//
// Source headers: aws-neuronx-runtime-lib 2.34.10.0-ac18d186d
//   (https://apt.repos.neuron.amazonaws.com, installs to /opt/aws/neuron/include)
// The SDK headers themselves are NOT vendored: they are AWS "All Rights
// Reserved". Only this mechanically derived interface description is checked in.
//
// Generated on x86_64-unknown-linux-gnu, which is a platform libnrt actually
// runs on, using the real <linux/types.h> rather than headers/shim. Regenerating
// off Linux falls back to that shim and yields `__u32 = u32` / `__u64 = u64`
// instead of the `c_uint` / `c_ulonglong` below. Those are the same size,
// alignment, and signedness, so either spelling is layout-correct, but the
// Linux-generated form is the faithful one and is what belongs here.
//
// Regenerate on a host with the SDK installed:
//   cargo build -p libnrt-rs --features bindgen
// then copy $OUT_DIR/bindings.rs over this file.

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::std::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const NRT_MAJOR_VERSION: u32 = 2;
pub const NRT_MINOR_VERSION: u32 = 0;
pub const NRT_TENSOR_NAME_MAX: u32 = 256;
pub const NRT_STATUS_NRT_SUCCESS: NRT_STATUS = 0;
pub const NRT_STATUS_NRT_FAILURE: NRT_STATUS = 1;
pub const NRT_STATUS_NRT_INVALID: NRT_STATUS = 2;
pub const NRT_STATUS_NRT_INVALID_HANDLE: NRT_STATUS = 3;
pub const NRT_STATUS_NRT_RESOURCE: NRT_STATUS = 4;
pub const NRT_STATUS_NRT_TIMEOUT: NRT_STATUS = 5;
pub const NRT_STATUS_NRT_HW_ERROR: NRT_STATUS = 6;
pub const NRT_STATUS_NRT_QUEUE_FULL: NRT_STATUS = 7;
pub const NRT_STATUS_NRT_LOAD_NOT_ENOUGH_NC: NRT_STATUS = 9;
pub const NRT_STATUS_NRT_UNSUPPORTED_NEFF_VERSION: NRT_STATUS = 10;
pub const NRT_STATUS_NRT_FAIL_HOST_MEM_ALLOC: NRT_STATUS = 11;
pub const NRT_STATUS_NRT_UNINITIALIZED: NRT_STATUS = 13;
pub const NRT_STATUS_NRT_CLOSED: NRT_STATUS = 14;
pub const NRT_STATUS_NRT_QUEUE_EMPTY: NRT_STATUS = 15;
pub const NRT_STATUS_NRT_EXEC_UNIT_UNRECOVERABLE: NRT_STATUS = 101;
pub const NRT_STATUS_NRT_EXEC_BAD_INPUT: NRT_STATUS = 1002;
pub const NRT_STATUS_NRT_EXEC_COMPLETED_WITH_NUM_ERR: NRT_STATUS = 1003;
pub const NRT_STATUS_NRT_EXEC_COMPLETED_WITH_ERR: NRT_STATUS = 1004;
pub const NRT_STATUS_NRT_EXEC_NC_BUSY: NRT_STATUS = 1005;
pub const NRT_STATUS_NRT_EXEC_OOB: NRT_STATUS = 1006;
pub const NRT_STATUS_NRT_COLL_PENDING: NRT_STATUS = 1100;
pub const NRT_STATUS_NRT_EXEC_HW_ERR_COLLECTIVES: NRT_STATUS = 1200;
pub const NRT_STATUS_NRT_EXEC_HW_ERR_HBM_UE: NRT_STATUS = 1201;
pub const NRT_STATUS_NRT_EXEC_HW_ERR_NC_UE: NRT_STATUS = 1202;
pub const NRT_STATUS_NRT_EXEC_HW_ERR_DMA_ABORT: NRT_STATUS = 1203;
pub const NRT_STATUS_NRT_EXEC_SW_NQ_OVERFLOW: NRT_STATUS = 1204;
pub const NRT_STATUS_NRT_EXEC_HW_ERR_REPAIRABLE_HBM_UE: NRT_STATUS = 1205;
pub const NRT_STATUS_NRT_NETWORK_PROXY_FAILURE: NRT_STATUS = 1206;
pub type NRT_STATUS = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn nrt_get_status_as_str(status: NRT_STATUS) -> *const ::std::os::raw::c_char;
}
pub type nrt_tensor_batch_offset_t = u64;
pub type nrt_tensor_batch_size_t = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_tensor_batch_op {
    pub offset: nrt_tensor_batch_offset_t,
    pub size: nrt_tensor_batch_size_t,
    pub buffer: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_tensor_batch_op"][::std::mem::size_of::<nrt_tensor_batch_op>() - 24usize];
    ["Alignment of nrt_tensor_batch_op"][::std::mem::align_of::<nrt_tensor_batch_op>() - 8usize];
    ["Offset of field: nrt_tensor_batch_op::offset"]
        [::std::mem::offset_of!(nrt_tensor_batch_op, offset) - 0usize];
    ["Offset of field: nrt_tensor_batch_op::size"]
        [::std::mem::offset_of!(nrt_tensor_batch_op, size) - 8usize];
    ["Offset of field: nrt_tensor_batch_op::buffer"]
        [::std::mem::offset_of!(nrt_tensor_batch_op, buffer) - 16usize];
};
pub type nrt_tensor_batch_op_t = nrt_tensor_batch_op;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_model {
    _unused: [u8; 0],
}
pub type nrt_model_t = nrt_model;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_tensor {
    _unused: [u8; 0],
}
pub type nrt_tensor_t = nrt_tensor;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_cc_context {
    _unused: [u8; 0],
}
pub type nrt_cc_context_t = nrt_cc_context;
pub const nrt_tensor_placement_t_NRT_TENSOR_PLACEMENT_DEVICE: nrt_tensor_placement_t = 0;
pub const nrt_tensor_placement_t_NRT_TENSOR_PLACEMENT_HOST: nrt_tensor_placement_t = 1;
pub type nrt_tensor_placement_t = ::std::os::raw::c_uint;
pub const nrt_framework_type_t_NRT_FRAMEWORK_TYPE_INVALID: nrt_framework_type_t = 0;
pub const nrt_framework_type_t_NRT_FRAMEWORK_TYPE_NO_FW: nrt_framework_type_t = 1;
pub const nrt_framework_type_t_NRT_FRAMEWORK_TYPE_TENSORFLOW: nrt_framework_type_t = 2;
pub const nrt_framework_type_t_NRT_FRAMEWORK_TYPE_PYTORCH: nrt_framework_type_t = 3;
pub const nrt_framework_type_t_NRT_FRAMEWORK_TYPE_MXNET: nrt_framework_type_t = 4;
pub const nrt_framework_type_t_NRT_FRAMEWORK_TYPE_PRECHECK: nrt_framework_type_t = 5;
pub type nrt_framework_type_t = ::std::os::raw::c_uint;
pub const NRT_INSTANCE_UNKNOWN: _bindgen_ty_1 = 0;
pub const NRT_INSTANCE_INF1: _bindgen_ty_1 = 1;
pub const NRT_INSTANCE_TRN1: _bindgen_ty_1 = 2;
pub const NRT_INSTANCE_TRN1N: _bindgen_ty_1 = 3;
pub const NRT_INSTANCE_INF2: _bindgen_ty_1 = 4;
pub const NRT_INSTANCE_TRN2: _bindgen_ty_1 = 5;
pub const NRT_INSTANCE_TRN2N: _bindgen_ty_1 = 6;
pub const NRT_INSTANCE_INF2E: _bindgen_ty_1 = 7;
pub const NRT_INSTANCE_TRN2P: _bindgen_ty_1 = 8;
pub const NRT_INSTANCE_TRN2U: _bindgen_ty_1 = 9;
pub const NRT_INSTANCE_TRN2E: _bindgen_ty_1 = 10;
pub const NRT_INSTANCE_TRN2EU: _bindgen_ty_1 = 11;
pub const NRT_INSTANCE_TRN2AC: _bindgen_ty_1 = 12;
pub const NRT_INSTANCE_TRN2UAC: _bindgen_ty_1 = 13;
pub const NRT_INSTANCE_TRN3: _bindgen_ty_1 = 14;
pub const NRT_INSTANCE_TRN3PDS98: _bindgen_ty_1 = 15;
pub const NRT_INSTANCE_TRN2EN: _bindgen_ty_1 = 16;
pub const NRT_INSTANCE_TRN3E: _bindgen_ty_1 = 17;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub const NRT_INSTANCE_SIZE_1XL: _bindgen_ty_2 = 0;
pub const NRT_INSTANCE_SIZE_2XL: _bindgen_ty_2 = 1;
pub const NRT_INSTANCE_SIZE_4XL: _bindgen_ty_2 = 2;
pub const NRT_INSTANCE_SIZE_6XL: _bindgen_ty_2 = 3;
pub const NRT_INSTANCE_SIZE_8XL: _bindgen_ty_2 = 4;
pub const NRT_INSTANCE_SIZE_24XL: _bindgen_ty_2 = 5;
pub const NRT_INSTANCE_SIZE_32XL: _bindgen_ty_2 = 6;
pub const NRT_INSTANCE_SIZE_48XL: _bindgen_ty_2 = 7;
pub const NRT_INSTANCE_SIZE_3XL: _bindgen_ty_2 = 8;
pub const NRT_INSTANCE_SIZE_UNKNOWN: _bindgen_ty_2 = 9;
pub const NRT_INSTANCE_SIZE_NUM: _bindgen_ty_2 = 9;
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
pub const nrt_op_type_NRT_OP_ADD: nrt_op_type = 0;
pub const nrt_op_type_NRT_OP_FMA: nrt_op_type = 1;
pub const nrt_op_type_NRT_OP_MAX: nrt_op_type = 2;
pub const nrt_op_type_NRT_OP_MIN: nrt_op_type = 3;
pub const nrt_op_type_NRT_OP_INVALID: nrt_op_type = 15;
pub type nrt_op_type = ::std::os::raw::c_uint;
pub use self::nrt_op_type as nrt_op_type_t;
pub const nrt_dtype_NRT_DTYPE_UNKNOWN: nrt_dtype = 0;
pub const nrt_dtype_NRT_DTYPE_INVALID: nrt_dtype = 0;
pub const nrt_dtype_NRT_DTYPE_FP8_E3: nrt_dtype = 13;
pub const nrt_dtype_NRT_DTYPE_FP8_E4: nrt_dtype = 14;
pub const nrt_dtype_NRT_DTYPE_FP8_E5: nrt_dtype = 15;
pub const nrt_dtype_NRT_DTYPE_FLOAT16: nrt_dtype = 7;
pub const nrt_dtype_NRT_DTYPE_BFLOAT16: nrt_dtype = 6;
pub const nrt_dtype_NRT_DTYPE_FLOAT32: nrt_dtype = 10;
pub const nrt_dtype_NRT_DTYPE_FP32R: nrt_dtype = 11;
pub const nrt_dtype_NRT_DTYPE_UINT8: nrt_dtype = 3;
pub const nrt_dtype_NRT_DTYPE_UINT16: nrt_dtype = 5;
pub const nrt_dtype_NRT_DTYPE_UINT32: nrt_dtype = 9;
pub const nrt_dtype_NRT_DTYPE_UINT64: nrt_dtype = 1;
pub const nrt_dtype_NRT_DTYPE_INT8: nrt_dtype = 2;
pub const nrt_dtype_NRT_DTYPE_INT16: nrt_dtype = 4;
pub const nrt_dtype_NRT_DTYPE_INT32: nrt_dtype = 8;
pub const nrt_dtype_NRT_DTYPE_INT64: nrt_dtype = 12;
pub type nrt_dtype = ::std::os::raw::c_uint;
pub use self::nrt_dtype as nrt_dtype_t;
pub const nrt_cc_op_type_NRT_CC_ALLGATHER: nrt_cc_op_type = 0;
pub const nrt_cc_op_type_NRT_CC_ALLREDUCE: nrt_cc_op_type = 1;
pub const nrt_cc_op_type_NRT_CC_REDUCESCATTER: nrt_cc_op_type = 2;
pub type nrt_cc_op_type = ::std::os::raw::c_uint;
pub use self::nrt_cc_op_type as nrt_cc_op_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_instance_info {
    pub family: u32,
    pub size: u32,
    pub arch_name: [::std::os::raw::c_char; 16usize],
    pub device_revision: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_instance_info"][::std::mem::size_of::<nrt_instance_info>() - 32usize];
    ["Alignment of nrt_instance_info"][::std::mem::align_of::<nrt_instance_info>() - 4usize];
    ["Offset of field: nrt_instance_info::family"]
        [::std::mem::offset_of!(nrt_instance_info, family) - 0usize];
    ["Offset of field: nrt_instance_info::size"]
        [::std::mem::offset_of!(nrt_instance_info, size) - 4usize];
    ["Offset of field: nrt_instance_info::arch_name"]
        [::std::mem::offset_of!(nrt_instance_info, arch_name) - 8usize];
    ["Offset of field: nrt_instance_info::device_revision"]
        [::std::mem::offset_of!(nrt_instance_info, device_revision) - 24usize];
};
pub type nrt_instance_info_t = nrt_instance_info;
unsafe extern "C" {
    pub fn nrt_get_instance_info(
        info: *mut nrt_instance_info_t,
        instance_info_len: usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_init(
        framework: nrt_framework_type_t,
        fw_version: *const ::std::os::raw::c_char,
        fal_version: *const ::std::os::raw::c_char,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_close();
}
unsafe extern "C" {
    pub fn nrt_load(
        neff_bytes: *const ::std::os::raw::c_void,
        size: usize,
        vnc: i32,
        vnc_count: i32,
        model: *mut *mut nrt_model_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_load_collectives(
        neff_bytes: *const ::std::os::raw::c_void,
        size: usize,
        vnc: i32,
        vnc_count: i32,
        ctx_device_id: u32,
        ctx_device_count: u32,
        model: *mut *mut nrt_model_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_unload(model: *mut nrt_model_t) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_model_nc_count(model: *const nrt_model_t, vnc_count: *mut u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_model_vnc_count(model: *const nrt_model_t, vnc_count: *mut u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_total_nc_count(vnc_count: *mut u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_total_vnc_count(vnc_count: *mut u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_visible_nc_count(vnc_count: *mut u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_visible_vnc_count(vnc_count: *mut u32) -> NRT_STATUS;
}
pub type nrt_tensor_set_t = ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn nrt_allocate_tensor_set(result: *mut *mut nrt_tensor_set_t) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_destroy_tensor_set(tensor_set: *mut *mut nrt_tensor_set_t);
}
unsafe extern "C" {
    pub fn nrt_add_tensor_to_tensor_set(
        tensor_set: *mut nrt_tensor_set_t,
        tensor_name: *const ::std::os::raw::c_char,
        tensor: *mut nrt_tensor_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_tensor_from_tensor_set(
        tensor_set: *mut nrt_tensor_set_t,
        tensor_name: *const ::std::os::raw::c_char,
        tensor: *mut *mut nrt_tensor_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_execute(
        model: *mut nrt_model_t,
        input_set: *const nrt_tensor_set_t,
        output_set: *mut nrt_tensor_set_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_execute_repeat(
        model: *mut nrt_model_t,
        input_set: *const nrt_tensor_set_t,
        output_set: *mut nrt_tensor_set_t,
        repeat_count: ::std::os::raw::c_int,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_build_global_comm(vnc: i32, g_device_id: u32, g_device_count: u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_allocate(
        tensor_placement: nrt_tensor_placement_t,
        vnc: ::std::os::raw::c_int,
        size: usize,
        name: *const ::std::os::raw::c_char,
        tensor: *mut *mut nrt_tensor_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_free(tensor: *mut *mut nrt_tensor_t);
}
unsafe extern "C" {
    pub fn nrt_tensor_read(
        tensor: *const nrt_tensor_t,
        buf: *mut ::std::os::raw::c_void,
        offset: usize,
        size: usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_write(
        tensor: *mut nrt_tensor_t,
        buf: *const ::std::os::raw::c_void,
        offset: usize,
        size: usize,
    ) -> NRT_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_tensor_batch {
    pub tensor: *const nrt_tensor_t,
    pub ops: *const nrt_tensor_batch_op_t,
    pub num_ops: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_tensor_batch"][::std::mem::size_of::<nrt_tensor_batch>() - 24usize];
    ["Alignment of nrt_tensor_batch"][::std::mem::align_of::<nrt_tensor_batch>() - 8usize];
    ["Offset of field: nrt_tensor_batch::tensor"]
        [::std::mem::offset_of!(nrt_tensor_batch, tensor) - 0usize];
    ["Offset of field: nrt_tensor_batch::ops"]
        [::std::mem::offset_of!(nrt_tensor_batch, ops) - 8usize];
    ["Offset of field: nrt_tensor_batch::num_ops"]
        [::std::mem::offset_of!(nrt_tensor_batch, num_ops) - 16usize];
};
pub type nrt_tensor_batch_t = nrt_tensor_batch;
unsafe extern "C" {
    pub fn nrt_tensor_read_batch(
        batches: *const nrt_tensor_batch_t,
        num_batches: u64,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_write_batch(
        batches: *const nrt_tensor_batch_t,
        num_batches: u64,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_copy(
        src: *const nrt_tensor_t,
        src_offset: usize,
        dst: *mut nrt_tensor_t,
        dst_offset: usize,
        size: usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_get_size(tensor: *const nrt_tensor_t) -> usize;
}
unsafe extern "C" {
    pub fn nrt_tensor_memset(
        tensor: *mut nrt_tensor_t,
        offset: u64,
        value: ::std::os::raw::c_int,
        size: usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_allocate_empty(
        name: *const ::std::os::raw::c_char,
        tensor: *mut *mut nrt_tensor_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_attach_buffer(
        tensor: *mut nrt_tensor_t,
        buffer: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_allocate_slice(
        tensor_source: *const nrt_tensor_t,
        offset: usize,
        size: usize,
        name: *const ::std::os::raw::c_char,
        tensor_slice: *mut *mut nrt_tensor_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_get_va(tensor: *const nrt_tensor_t) -> *mut ::std::os::raw::c_void;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_tensor_device_allocation_info {
    pub physical_address: u64,
    pub size: usize,
    pub hbm_index: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_tensor_device_allocation_info"]
        [::std::mem::size_of::<nrt_tensor_device_allocation_info>() - 24usize];
    ["Alignment of nrt_tensor_device_allocation_info"]
        [::std::mem::align_of::<nrt_tensor_device_allocation_info>() - 8usize];
    ["Offset of field: nrt_tensor_device_allocation_info::physical_address"]
        [::std::mem::offset_of!(nrt_tensor_device_allocation_info, physical_address) - 0usize];
    ["Offset of field: nrt_tensor_device_allocation_info::size"]
        [::std::mem::offset_of!(nrt_tensor_device_allocation_info, size) - 8usize];
    ["Offset of field: nrt_tensor_device_allocation_info::hbm_index"]
        [::std::mem::offset_of!(nrt_tensor_device_allocation_info, hbm_index) - 16usize];
};
pub type nrt_tensor_device_allocation_info_t = nrt_tensor_device_allocation_info;
unsafe extern "C" {
    pub fn nrt_tensor_get_device_allocation_info(
        tensor: *const nrt_tensor_t,
        alloc_info: *mut nrt_tensor_device_allocation_info_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_check_output_completion(
        output_tensor: *const nrt_tensor_t,
        timeout: i64,
        expected_completion_count: u64,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_tensor_reset_output_completion(output_tensor: *mut nrt_tensor_t) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_dmabuf_fd(va: u64, size: u64, fd: *mut ::std::os::raw::c_int) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_dmabuf_fd_v2(
        va: u64,
        size: u64,
        fd: *mut ::std::os::raw::c_int,
        offset: *mut u64,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_host_device_id_get(
        neuron_dev: ::std::os::raw::c_int,
        host_device_id: *mut u32,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_host_device_id_rid_map_get(
        count: *mut u32,
        host_did_to_rid_map: *mut u32,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_hbm_mmap_va(
        device_id: ::std::os::raw::c_int,
        hbm_idx: ::std::os::raw::c_int,
        addr: *mut *mut ::std::os::raw::c_void,
        size: *mut usize,
    ) -> NRT_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_vnc_memory_stats {
    pub bytes_used: usize,
    pub bytes_limit: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_vnc_memory_stats"][::std::mem::size_of::<nrt_vnc_memory_stats>() - 16usize];
    ["Alignment of nrt_vnc_memory_stats"][::std::mem::align_of::<nrt_vnc_memory_stats>() - 8usize];
    ["Offset of field: nrt_vnc_memory_stats::bytes_used"]
        [::std::mem::offset_of!(nrt_vnc_memory_stats, bytes_used) - 0usize];
    ["Offset of field: nrt_vnc_memory_stats::bytes_limit"]
        [::std::mem::offset_of!(nrt_vnc_memory_stats, bytes_limit) - 8usize];
};
pub type nrt_vnc_memory_stats_t = nrt_vnc_memory_stats;
unsafe extern "C" {
    pub fn nrt_get_vnc_memory_stats(
        vnc: u32,
        stats: *mut nrt_vnc_memory_stats_t,
        stats_size_in: usize,
        stats_size_out: *mut usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_attached_efa_bdf(
        va: *const ::std::os::raw::c_void,
        efa_bdf: *mut ::std::os::raw::c_char,
        len: *mut usize,
    ) -> NRT_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_cc_comm {
    pub replica_group: *mut u32,
    pub rank: u32,
    pub rank_n: u32,
    pub ctx_device_id: u32,
    pub ctx_device_count: u32,
    pub vnc: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_cc_comm"][::std::mem::size_of::<nrt_cc_comm>() - 32usize];
    ["Alignment of nrt_cc_comm"][::std::mem::align_of::<nrt_cc_comm>() - 8usize];
    ["Offset of field: nrt_cc_comm::replica_group"]
        [::std::mem::offset_of!(nrt_cc_comm, replica_group) - 0usize];
    ["Offset of field: nrt_cc_comm::rank"][::std::mem::offset_of!(nrt_cc_comm, rank) - 8usize];
    ["Offset of field: nrt_cc_comm::rank_n"][::std::mem::offset_of!(nrt_cc_comm, rank_n) - 12usize];
    ["Offset of field: nrt_cc_comm::ctx_device_id"]
        [::std::mem::offset_of!(nrt_cc_comm, ctx_device_id) - 16usize];
    ["Offset of field: nrt_cc_comm::ctx_device_count"]
        [::std::mem::offset_of!(nrt_cc_comm, ctx_device_count) - 20usize];
    ["Offset of field: nrt_cc_comm::vnc"][::std::mem::offset_of!(nrt_cc_comm, vnc) - 24usize];
};
pub type nrt_cc_comm_t = nrt_cc_comm;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_cc_param {
    pub num_ops: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_cc_param"][::std::mem::size_of::<nrt_cc_param>() - 4usize];
    ["Alignment of nrt_cc_param"][::std::mem::align_of::<nrt_cc_param>() - 4usize];
    ["Offset of field: nrt_cc_param::num_ops"]
        [::std::mem::offset_of!(nrt_cc_param, num_ops) - 0usize];
};
pub type nrt_cc_param_t = nrt_cc_param;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_tensor_list {
    pub tensors: *mut *mut nrt_tensor_t,
    pub num_tensors: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_tensor_list"][::std::mem::size_of::<nrt_tensor_list>() - 16usize];
    ["Alignment of nrt_tensor_list"][::std::mem::align_of::<nrt_tensor_list>() - 8usize];
    ["Offset of field: nrt_tensor_list::tensors"]
        [::std::mem::offset_of!(nrt_tensor_list, tensors) - 0usize];
    ["Offset of field: nrt_tensor_list::num_tensors"]
        [::std::mem::offset_of!(nrt_tensor_list, num_tensors) - 8usize];
};
pub type nrt_tensor_list_t = nrt_tensor_list;
unsafe extern "C" {
    pub fn nrt_cc_global_comm_init(vnc: u32, g_device_id: u32, g_device_count: u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_cc_create_stream(stream_id: u32) -> NRT_STATUS;
}
pub const nrt_pinned_alloc_type_t_NRT_PINNED_MALLOC: nrt_pinned_alloc_type_t = 0;
pub const nrt_pinned_alloc_type_t_NRT_PINNED_HUGEPAGE_2M: nrt_pinned_alloc_type_t = 1;
pub const nrt_pinned_alloc_type_t_NRT_PINNED_HUGEPAGE_1G: nrt_pinned_alloc_type_t = 2;
pub type nrt_pinned_alloc_type_t = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn nrt_pinned_malloc(
        size: usize,
        type_: nrt_pinned_alloc_type_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn nrt_pinned_free(ptr: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn nrt_tensor_get_lnc_index(
        tensor: *const nrt_tensor_t,
        lnc_idx: *mut ::std::os::raw::c_int,
    ) -> NRT_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_version {
    pub rt_major: u64,
    pub rt_minor: u64,
    pub rt_patch: u64,
    pub rt_maintenance: u64,
    pub rt_detail: [::std::os::raw::c_char; 128usize],
    pub git_hash: [::std::os::raw::c_char; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_version"][::std::mem::size_of::<nrt_version>() - 224usize];
    ["Alignment of nrt_version"][::std::mem::align_of::<nrt_version>() - 8usize];
    ["Offset of field: nrt_version::rt_major"]
        [::std::mem::offset_of!(nrt_version, rt_major) - 0usize];
    ["Offset of field: nrt_version::rt_minor"]
        [::std::mem::offset_of!(nrt_version, rt_minor) - 8usize];
    ["Offset of field: nrt_version::rt_patch"]
        [::std::mem::offset_of!(nrt_version, rt_patch) - 16usize];
    ["Offset of field: nrt_version::rt_maintenance"]
        [::std::mem::offset_of!(nrt_version, rt_maintenance) - 24usize];
    ["Offset of field: nrt_version::rt_detail"]
        [::std::mem::offset_of!(nrt_version, rt_detail) - 32usize];
    ["Offset of field: nrt_version::git_hash"]
        [::std::mem::offset_of!(nrt_version, git_hash) - 160usize];
};
pub type nrt_version_t = nrt_version;
unsafe extern "C" {
    pub fn nrt_get_version(ver: *mut nrt_version_t, size: usize) -> NRT_STATUS;
}
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct neuron_ioctl_mem_chunk_info {
    pub pa: __u64,
    pub size: __u64,
    pub mem_type: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of neuron_ioctl_mem_chunk_info"]
        [::std::mem::size_of::<neuron_ioctl_mem_chunk_info>() - 24usize];
    ["Alignment of neuron_ioctl_mem_chunk_info"]
        [::std::mem::align_of::<neuron_ioctl_mem_chunk_info>() - 8usize];
    ["Offset of field: neuron_ioctl_mem_chunk_info::pa"]
        [::std::mem::offset_of!(neuron_ioctl_mem_chunk_info, pa) - 0usize];
    ["Offset of field: neuron_ioctl_mem_chunk_info::size"]
        [::std::mem::offset_of!(neuron_ioctl_mem_chunk_info, size) - 8usize];
    ["Offset of field: neuron_ioctl_mem_chunk_info::mem_type"]
        [::std::mem::offset_of!(neuron_ioctl_mem_chunk_info, mem_type) - 16usize];
};
pub const nrt_tensor_usage_NRT_TENSOR_USAGE_INPUT: nrt_tensor_usage = 0;
pub const nrt_tensor_usage_NRT_TENSOR_USAGE_OUTPUT: nrt_tensor_usage = 1;
pub type nrt_tensor_usage = ::std::os::raw::c_uint;
pub use self::nrt_tensor_usage as nrt_tensor_usage_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_tensor_info {
    pub name: [::std::os::raw::c_char; 256usize],
    pub usage: nrt_tensor_usage_t,
    pub size: usize,
    pub dtype: nrt_dtype_t,
    pub shape: *mut u32,
    pub ndim: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_tensor_info"][::std::mem::size_of::<nrt_tensor_info>() - 296usize];
    ["Alignment of nrt_tensor_info"][::std::mem::align_of::<nrt_tensor_info>() - 8usize];
    ["Offset of field: nrt_tensor_info::name"]
        [::std::mem::offset_of!(nrt_tensor_info, name) - 0usize];
    ["Offset of field: nrt_tensor_info::usage"]
        [::std::mem::offset_of!(nrt_tensor_info, usage) - 256usize];
    ["Offset of field: nrt_tensor_info::size"]
        [::std::mem::offset_of!(nrt_tensor_info, size) - 264usize];
    ["Offset of field: nrt_tensor_info::dtype"]
        [::std::mem::offset_of!(nrt_tensor_info, dtype) - 272usize];
    ["Offset of field: nrt_tensor_info::shape"]
        [::std::mem::offset_of!(nrt_tensor_info, shape) - 280usize];
    ["Offset of field: nrt_tensor_info::ndim"]
        [::std::mem::offset_of!(nrt_tensor_info, ndim) - 288usize];
};
pub type nrt_tensor_info_t = nrt_tensor_info;
#[repr(C)]
#[derive(Debug)]
pub struct nrt_tensor_info_array {
    pub tensor_count: u64,
    pub tensor_array: __IncompleteArrayField<nrt_tensor_info_t>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_tensor_info_array"][::std::mem::size_of::<nrt_tensor_info_array>() - 8usize];
    ["Alignment of nrt_tensor_info_array"]
        [::std::mem::align_of::<nrt_tensor_info_array>() - 8usize];
    ["Offset of field: nrt_tensor_info_array::tensor_count"]
        [::std::mem::offset_of!(nrt_tensor_info_array, tensor_count) - 0usize];
    ["Offset of field: nrt_tensor_info_array::tensor_array"]
        [::std::mem::offset_of!(nrt_tensor_info_array, tensor_array) - 8usize];
};
pub type nrt_tensor_info_array_t = nrt_tensor_info_array;
pub type NRT_ASYNC_EXEC_STATUS_CALLBACK = ::std::option::Option<
    unsafe extern "C" fn(
        params: *mut ::std::os::raw::c_void,
        model_id: u32,
        vnc: u32,
        job_id: u64,
        status: NRT_STATUS,
    ),
>;
unsafe extern "C" {
    pub fn nrt_get_model_tensor_info(
        model: *mut nrt_model_t,
        tensor_info: *mut *mut nrt_tensor_info_array_t,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_model_instance_count(
        model: *mut nrt_model_t,
        instance_count: *mut u32,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_free_model_tensor_info(tensor_info: *mut nrt_tensor_info_array_t) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_trace_start(trace_mem: bool) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_trace_stop(filename: *const ::std::os::raw::c_char) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_libnccl_net(
        err: *mut ::std::os::raw::c_int,
        err_msg: *mut ::std::os::raw::c_char,
        err_msg_size: usize,
    ) -> *mut ::std::os::raw::c_void;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_ucode_img {
    pub bin: *mut u8,
    pub size: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_ucode_img"][::std::mem::size_of::<nrt_ucode_img>() - 16usize];
    ["Alignment of nrt_ucode_img"][::std::mem::align_of::<nrt_ucode_img>() - 8usize];
    ["Offset of field: nrt_ucode_img::bin"][::std::mem::offset_of!(nrt_ucode_img, bin) - 0usize];
    ["Offset of field: nrt_ucode_img::size"][::std::mem::offset_of!(nrt_ucode_img, size) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_ucode_info {
    pub iram: nrt_ucode_img,
    pub dram: nrt_ucode_img,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_ucode_info"][::std::mem::size_of::<nrt_ucode_info>() - 32usize];
    ["Alignment of nrt_ucode_info"][::std::mem::align_of::<nrt_ucode_info>() - 8usize];
    ["Offset of field: nrt_ucode_info::iram"]
        [::std::mem::offset_of!(nrt_ucode_info, iram) - 0usize];
    ["Offset of field: nrt_ucode_info::dram"]
        [::std::mem::offset_of!(nrt_ucode_info, dram) - 16usize];
};
unsafe extern "C" {
    pub fn nrt_set_pool_eng_ucode(ucode_info: *const nrt_ucode_info) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_memcpy_to_device(
        dest: *mut ::std::os::raw::c_void,
        src: *const ::std::os::raw::c_void,
        size: usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_register_async_exec_callback(
        callback: NRT_ASYNC_EXEC_STATUS_CALLBACK,
        params: *mut ::std::os::raw::c_void,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_barrier(vnc: i32, g_device_id: u32, g_device_count: u32) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_all_gather(
        vnc: i32,
        g_device_id: u32,
        g_device_count: u32,
        rank_input_size: u32,
        input: *mut ::std::os::raw::c_void,
        output: *mut ::std::os::raw::c_void,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_async_drain_queued_execs(vnc: i32) -> NRT_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrt_model_info {
    pub vnc: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrt_model_info"][::std::mem::size_of::<nrt_model_info>() - 4usize];
    ["Alignment of nrt_model_info"][::std::mem::align_of::<nrt_model_info>() - 4usize];
    ["Offset of field: nrt_model_info::vnc"][::std::mem::offset_of!(nrt_model_info, vnc) - 0usize];
};
pub type nrt_model_info_t = nrt_model_info;
unsafe extern "C" {
    pub fn nrt_get_model_info(
        model: *const nrt_model_t,
        info: *mut nrt_model_info_t,
        info_size_in: usize,
        info_size_out: *mut usize,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_get_device_id(
        lnc_idx: ::std::os::raw::c_int,
        device_id: *mut ::std::os::raw::c_int,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_dump_device_allocation_info(
        lnc_idx: ::std::os::raw::c_int,
        data: *mut neuron_ioctl_mem_chunk_info,
        num_entries: *mut u32,
    ) -> NRT_STATUS;
}
unsafe extern "C" {
    pub fn nrt_debug_log_oom_report(lnc_idx: ::std::os::raw::c_int) -> NRT_STATUS;
}
