// Copyright (c) 2025 Pratik Barhate
// Licensed under the MIT License. See the LICENSE file in the project root for more information.

//! Raw, unsafe FFI types for the AWS Neuron runtime (`libnrt`) C API.
//!
//! Generated by `bindgen` from `headers/wrapper.h` against the headers shipped
//! in `aws-neuronx-runtime-lib` 2.34.10.0. Nothing here is hand-edited.
//!
//! This module contains the types, constants, and `extern "C"` declarations
//! bindgen produced. The declarations are reference only: `libnrt` exports plain
//! functions rather than a function-pointer table, so this crate resolves them
//! with `libloading` in the crate's private `symbols` module instead of
//! linking. Nothing here is
//! referenced by the crate's own code, which is why a binary built from it links
//! and runs on hosts with no Neuron SDK. Calling `sys::nrt_*` directly opts back
//! into build-time linking and will fail to link without `libnrt`.
//!
//! # A note on how these bindings were generated
//!
//! Neuron runs on Linux (x86-64 and aarch64), but the checked-in bindings were
//! generated on a macOS arm64 host. That is sound here because every type in
//! this API is built from `char`, `int`, `int32_t`, `uint32_t`, `uint64_t`,
//! `size_t`, pointers, and C enums, all of which have identical size,
//! alignment, and signedness across these LP64 targets. It is *not* a general
//! guarantee: if AWS ever adds a `long`, a bitfield, or a packed struct to this
//! API, regenerate on the target platform.
//!
//! To check for drift on a Neuron host:
//!
//! ```text
//! cargo build -p libnrt-rs --features bindgen
//! diff <(tail -n +15 src/bindings/nrt.rs) \
//!      "$(find target -name bindings.rs -path '*libnrt-rs*' | head -1)"
//! ```

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    // bindgen's `__IncompleteArrayField` helpers call `slice::from_raw_parts`
    // directly in the body of an `unsafe fn`, which edition 2024 flags. The
    // generated code is not ours to restructure.
    unsafe_op_in_unsafe_fn,
    clippy::all
)]

#[cfg(feature = "bindgen")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(not(feature = "bindgen"))]
include!("bindings/nrt.rs");
